import type { Claim, Rule, Stage, Task } from './types';

export const stages: Stage[] = [
  { id: 'ai-review', name: 'AI Review', color: '#3b82f6', bgColor: '#eff6ff' },
  { id: 'pending', name: 'Human Approval', color: '#f59e0b', bgColor: '#fffbeb' },
  { id: 'ready-to-submit', name: 'Ready To Submit', color: '#0ea5e9', bgColor: '#ecfeff' },
  { id: 'submitted', name: 'Claim Submitted', color: '#10b981', bgColor: '#ecfdf5' },
];

export const claims: Claim[] = [
  {
    id: 1,
    patient: 'Sarah Chen',
    dob: '03/15/1988',
    serviceDate: '12/24/2024',
    provider: 'Dr. Williams',
    facility: 'Main Office',
    mode: 'In-Person',
    cpt: ['90834'],
    modifiers: [],
    icd10: ['F41.1'],
    amount: 150,
    payer: 'Aetna',
    stage: 'submitted',
    status: 'In transit',
    timeInStage: '15m',
    isResubmission: false,
    memberId: 'MEM-001',
    phone: '(555) 111-2222',
  },
  {
    id: 2,
    patient: 'Michael Rodriguez',
    dob: '07/22/1975',
    serviceDate: '12/23/2024',
    provider: 'Dr. Chen',
    facility: 'Downtown Clinic',
    mode: 'Telehealth',
    cpt: ['90791'],
    modifiers: ['-95'],
    icd10: ['F32.9'],
    amount: 250,
    payer: 'United',
    stage: 'submitted',
    status: 'In transit',
    timeInStage: '1h',
    isResubmission: false,
    memberId: 'MEM-002',
    phone: '(555) 111-3333',
  },
  {
    id: 3,
    patient: 'Jennifer Park',
    dob: '01/30/1990',
    serviceDate: '12/24/2024',
    provider: 'Dr. Williams',
    facility: 'Main Office',
    mode: 'In-Person',
    cpt: ['90837'],
    modifiers: [],
    icd10: ['F43.10'],
    amount: 200,
    payer: 'Cigna',
    stage: 'submitted',
    status: 'In transit',
    timeInStage: '5m',
    isResubmission: false,
    memberId: 'MEM-003',
    phone: '(555) 111-4444',
  },
  {
    id: 4,
    patient: 'David Thompson',
    dob: '11/08/1982',
    serviceDate: '12/23/2024',
    provider: 'Dr. Smith',
    facility: 'North Campus',
    mode: 'Telehealth',
    cpt: ['90834'],
    modifiers: ['-GT'],
    icd10: ['F41.9'],
    amount: 150,
    payer: 'Blue Cross',
    stage: 'submitted',
    status: 'In transit',
    timeInStage: '12m',
    isResubmission: false,
    memberId: 'MEM-004',
    phone: '(555) 111-5555',
  },
  {
    id: 5,
    patient: 'Amanda Foster',
    dob: '09/14/1995',
    serviceDate: '12/22/2024',
    provider: 'Dr. Williams',
    facility: 'Main Office',
    mode: 'Telehealth',
    cpt: ['90834'],
    modifiers: [],
    icd10: ['F41.1'],
    amount: 150,
    payer: 'Aetna',
    stage: 'submitted',
    status: 'In transit',
    aiSuggestions: [
      { type: 'cpt', from: '90834', to: '90837', reason: 'Session duration: 52 min requires 90837', confidence: 93 },
      { type: 'modifier', add: '-GT', reason: 'Telehealth service indicator missing', confidence: 91 },
      { type: 'icd10', from: 'F41.1', to: 'F41.9', reason: 'Better matches clinical documentation', confidence: 84 },
    ],
    timeInStage: '2h',
    isResubmission: false,
    memberId: 'MEM-005',
    phone: '(555) 222-1111',
  },
  {
    id: 6,
    patient: 'James Liu',
    dob: '02/28/1980',
    serviceDate: '12/23/2024',
    provider: 'Dr. Chen',
    facility: 'Downtown Clinic',
    mode: 'Telehealth',
    cpt: ['90837'],
    modifiers: [],
    icd10: ['F32.9'],
    amount: 200,
    payer: 'Medicare',
    stage: 'submitted',
    status: 'In transit',
    aiSuggestions: [{ type: 'modifier', add: '-95', reason: 'Telehealth modifier required for Medicare', confidence: 88 }],
    timeInStage: '4h',
    isResubmission: false,
    memberId: 'MEM-006',
    phone: '(555) 222-3333',
  },
  {
    id: 7,
    patient: 'Lisa Martinez',
    dob: '04/18/1988',
    serviceDate: '12/20/2024',
    provider: 'Dr. Williams',
    facility: 'Main Office',
    mode: 'Telehealth',
    cpt: ['90834'],
    modifiers: ['-GT'],
    icd10: ['F43.12'],
    amount: 150,
    payer: 'United',
    stage: 'submitted',
    status: 'In transit',
    approvedBy: 'Sarah M.',
    approvedAt: '2:34 PM',
    aiSuggestions: [
      {
        type: 'cpt',
        from: '90834',
        to: '90837',
        reason: 'Session duration: 52 min requires 90837',
        approved: true,
        confidence: 94,
        autoApproved: true,
      },
      {
        type: 'modifier',
        add: '-GT',
        reason: 'Telehealth service indicator missing',
        approved: true,
        confidence: 93,
        autoApproved: true,
      },
    ],
    timeInStage: '6h',
    isResubmission: false,
    memberId: 'MEM-007',
    phone: '(555) 222-4444',
    activities: [
      {
        id: 'act-7-1',
        title: 'Auto-approved by AI',
        timestamp: '2:34 PM',
        detail: '2 high-confidence suggestions applied automatically',
        level: 'success',
      },
    ],
  },
  {
    id: 8,
    patient: 'Robert Kim',
    dob: '12/01/1970',
    serviceDate: '12/19/2024',
    provider: 'Dr. Smith',
    facility: 'North Campus',
    mode: 'Telehealth',
    cpt: ['90791'],
    modifiers: ['-GT'],
    icd10: ['F32.1'],
    amount: 250,
    payer: 'Cigna',
    stage: 'submitted',
    status: 'In transit',
    approvedBy: 'Mike R.',
    approvedAt: '1:15 PM',
    aiSuggestions: [
      {
        type: 'modifier',
        add: '-GT',
        reason: 'Telehealth service indicator',
        approved: true,
        confidence: 92,
        autoApproved: true,
      },
      {
        type: 'icd10',
        from: 'F32.1',
        to: 'F32.2',
        reason: 'Severity adjustment',
        approved: false,
        confidence: 76,
      },
    ],
    timeInStage: '1d',
    isResubmission: false,
    memberId: 'MEM-008',
    phone: '(555) 222-5555',
    activities: [
      {
        id: 'act-8-1',
        title: 'Partial auto-approval',
        timestamp: '1:15 PM',
        detail: 'Modifier auto-applied; ICD-10 requires human review',
        level: 'info',
      },
    ],
  },
  {
    id: 9,
    patient: 'Emily Watson',
    dob: '11/03/1992',
    serviceDate: '12/18/2024',
    provider: 'Dr. Chen',
    facility: 'Downtown Clinic',
    mode: 'In-Person',
    cpt: ['90834'],
    modifiers: [],
    icd10: ['F41.0'],
    amount: 150,
    payer: 'Aetna',
    stage: 'submitted',
    status: 'In transit',
    aiSuggestions: [{ type: 'modifier', add: '-59', reason: 'Distinct procedural service', confidence: 75 }],
    timeInStage: '3h',
    isResubmission: true,
    resubmissionAttempt: 2,
    previousRejection: 'Missing modifier -59',
    memberId: 'MEM-009',
    phone: '(555) 333-1111',
  },
  {
    id: 10,
    patient: 'Thomas Anderson',
    dob: '05/12/1982',
    serviceDate: '12/21/2024',
    provider: 'Dr. Williams',
    facility: 'Main Office',
    mode: 'In-Person',
    cpt: ['90837'],
    modifiers: [],
    icd10: ['F41.1'],
    amount: 200,
    payer: 'Blue Cross',
    stage: 'submitted',
    status: 'In transit',
    submittedAt: 'Dec 26, 10:30 AM',
    clearinghouse: 'Change Healthcare',
    timeInStage: '4h',
    isResubmission: false,
    memberId: 'MEM-010',
    phone: '(555) 333-2222',
  },
  {
    id: 11,
    patient: 'Maria Garcia',
    dob: '10/09/1978',
    serviceDate: '12/20/2024',
    provider: 'Dr. Smith',
    facility: 'North Campus',
    mode: 'Telehealth',
    cpt: ['90834'],
    modifiers: ['-95'],
    icd10: ['F43.10'],
    amount: 150,
    payer: 'Cigna',
    stage: 'submitted',
    status: 'Accepted',
    submittedAt: 'Dec 25, 3:45 PM',
    acceptedAt: 'Dec 26, 9:15 AM',
    clearinghouse: 'Waystar',
    timeInStage: '1d',
    isResubmission: false,
    memberId: 'MEM-011',
    phone: '(555) 333-3333',
  },
  {
    id: 12,
    patient: 'Kevin Wright',
    dob: '06/25/1993',
    serviceDate: '12/19/2024',
    provider: 'Dr. Chen',
    facility: 'Downtown Clinic',
    mode: 'In-Person',
    cpt: ['90791'],
    modifiers: [],
    icd10: ['F32.9'],
    amount: 250,
    payer: 'United',
    stage: 'submitted',
    status: 'Accepted',
    submittedAt: 'Dec 24, 2:20 PM',
    acceptedAt: 'Dec 25, 11:30 AM',
    clearinghouse: 'Change Healthcare',
    timeInStage: '2d',
    isResubmission: false,
    memberId: 'MEM-012',
    phone: '(555) 333-4444',
  },
  {
    id: 13,
    patient: 'Rachel Green',
    dob: '03/08/1985',
    serviceDate: '12/18/2024',
    provider: 'Dr. Williams',
    facility: 'Main Office',
    mode: 'In-Person',
    cpt: ['90834'],
    modifiers: [],
    icd10: ['F41.9'],
    amount: 150,
    payer: 'Aetna',
    stage: 'submitted',
    status: 'Rejected',
    submittedAt: 'Dec 23, 4:15 PM',
    rejectedAt: 'Dec 25, 3:42 PM',
    rejectionReason: 'Missing coordination of benefits information',
    rejectionCode: 'COB-123',
    clearinghouse: 'Change Healthcare',
    timeInStage: '3d',
    isResubmission: false,
    memberId: 'MEM-013',
    phone: '(555) 333-5555',
  },
  {
    id: 14,
    patient: 'Daniel Lee',
    dob: '07/17/1972',
    serviceDate: '12/17/2024',
    provider: 'Dr. Smith',
    facility: 'North Campus',
    mode: 'Telehealth',
    cpt: ['90837'],
    modifiers: ['-95', '-GT'],
    icd10: ['F32.1'],
    amount: 200,
    payer: 'Medicare',
    stage: 'submitted',
    status: 'Rejected',
    submittedAt: 'Dec 22, 1:30 PM',
    rejectedAt: 'Dec 24, 10:20 AM',
    rejectionReason: 'Invalid modifier combination',
    rejectionCode: 'MOD-456',
    clearinghouse: 'Waystar',
    timeInStage: '4d',
    isResubmission: false,
    memberId: 'MEM-014',
    phone: '(555) 444-1111',
  },
];

export const rules: Rule[] = [
  {
    id: 'r1',
    name: 'Telehealth Modifier Requirement',
    description: 'Require -95 or -GT on all telehealth visits before submission.',
  },
  {
    id: 'r2',
    name: 'Timely Filing Check',
    description: 'Block submission if DOS is more than 60 days without authorization.',
  },
  {
    id: 'r3',
    name: 'POS Validation',
    description: 'Ensure POS 02 when visit mode is telehealth to avoid payer rejections.',
  },
];

export const ehrSyncBatches: Claim[][] = [
  [
    {
      id: 15,
      patient: 'Olivia Benson',
      dob: '02/14/1987',
      serviceDate: '01/02/2025',
      provider: 'Dr. Lee',
      facility: 'Telehealth Clinic',
      mode: 'Telehealth',
      providerState: 'CA',
      patientState: 'CA',
      cpt: ['90837'],
      modifiers: [],
      icd10: ['F41.1'],
      amount: 200,
      payer: 'Aetna',
      stage: 'ai-review',
      status: 'Issues detected: missing telehealth modifier',
      timeInStage: '2m',
      isResubmission: false,
      memberId: 'MEM-015',
      phone: '(555) 666-7777',
      placeOfServiceCode: '02',
      placeOfServiceDescription: 'Telehealth Provided Other than in Patient’s Home',
      serviceType: 'Individual Therapy - Telehealth',
      location: 'Patient at home (telehealth)',
      telehealthPlatform: 'Zoom for Healthcare',
      aiSuggestions: [
        {
          type: 'modifier',
          add: '-95',
          reason: 'Telehealth visit billed without required 95 modifier; payer requires POS 02 + modifier 95 for reimbursement.',
          confidence: 95,
        },
      ],
      clinicalQuickFacts: [
        { title: 'Session Setting', value: 'Telehealth video visit' },
        { title: 'Expected POS', value: '02 - Telehealth', prominent: true },
        { title: 'Modifier', value: 'Missing 95 modifier' },
        { title: 'Platform', value: 'Zoom for Healthcare' },
      ],
      clinicalNoteSections: [
        {
          label: 'OBJECTIVE',
          text:
            'Session conducted via secure video; patient in home environment. No technical issues noted. Provider confirmed patient location and consent for telehealth.',
        },
        {
          label: 'ASSESSMENT',
          text:
            'Generalized Anxiety Disorder (F41.1). Telehealth appropriate; no safety concerns reported. Continues CBT-focused plan.',
        },
      ],
    },
    {
      id: 16,
      patient: 'Noah Price',
      dob: '06/11/1985',
      serviceDate: '01/03/2025',
      provider: 'Dr. Smith',
      facility: 'Frederick Clinic',
      mode: 'Telehealth',
      providerState: 'MD',
      patientState: 'MD',
      cpt: ['90791'],
      modifiers: ['-GT'],
      icd10: ['F32.1'],
      amount: 250,
      payer: 'United',
      stage: 'ai-review',
      status: 'Issue detected: place of service mismatch',
      timeInStage: '1m',
      isResubmission: false,
      memberId: 'MEM-016',
      phone: '(555) 777-8888',
      placeOfServiceCode: '11',
      placeOfServiceDescription: 'Office',
      expectedPlaceOfServiceCode: '02',
      expectedPlaceOfServiceDescription: 'Telehealth Provided Other than in Patient’s Home',
      serviceType: 'Telehealth intake (scheduled virtual)',
      location: 'Frederick Clinic - Room 3B (documented physical location)',
      telehealthPlatform: 'Doxy.me',
      aiSuggestions: [
        {
          type: 'pos',
          from: '11 - Office',
          to: '02 - Telehealth',
          reason:
            'Progress note documents a virtual session; place of service should be 02 for telehealth instead of 11 (office).',
          confidence: 82,
        },
      ],
      clinicalQuickFacts: [
        { title: 'Session Type', value: 'Telehealth (scheduled virtual)' },
        { title: 'Documented POS', value: '11 - Office' },
        { title: 'Expected POS', value: '02 - Telehealth', prominent: true },
        { title: 'Location in Note', value: 'Frederick Clinic - Room 3B' },
      ],
      clinicalNoteSections: [
        {
          label: 'OBJECTIVE',
          text:
            'Provider documented patient “connected via video from Frederick Clinic room 3B” even though visit was billed as telehealth.',
        },
        {
          label: 'ASSESSMENT',
          text:
            'Depressive episode (F32.1). Telehealth encounter; POS should reflect telehealth. Location field suggests in-office coding.',
        },
      ],
      relatedDocuments: [
        { title: 'Progress Note - Jan 3', date: 'Jan 3, 2025', cta: 'View' },
        { title: 'Telehealth Consent', date: 'On file', cta: 'View' },
      ],
    },
    {
      id: 17,
      patient: 'Priya Desai',
      dob: '09/02/1991',
      serviceDate: '01/03/2025',
      provider: 'Dr. Patel',
      facility: 'Telehealth Clinic',
      mode: 'Telehealth',
      providerState: 'CA',
      patientState: 'CA',
      cpt: ['90834'],
      modifiers: [],
      icd10: ['F41.1'],
      amount: 180,
      payer: 'Blue Cross',
      stage: 'ai-review',
      status: 'Issue detected: missing telehealth modifier',
      timeInStage: 'Just now',
      isResubmission: false,
      memberId: 'MEM-017',
      phone: '(555) 777-9999',
      aiSuggestions: [
        {
          type: 'modifier',
          add: '-95',
          reason:
            'Telehealth visit billed without required 95 modifier; add modifier 95 to meet payer telehealth billing rules.',
          confidence: 94,
        },
      ],
    },
    {
      id: 18,
      patient: 'Ethan Morales',
      dob: '12/12/1984',
      serviceDate: '01/02/2025',
      provider: 'Dr. Smith',
      facility: 'Telehealth Clinic',
      mode: 'Telehealth',
      providerState: 'CA',
      patientState: 'CA',
      cpt: ['90791'],
      modifiers: [],
      icd10: ['F32.9'],
      amount: 230,
      payer: 'Cigna',
      stage: 'ai-review',
      status: 'Issue detected: missing telehealth modifier',
      timeInStage: 'Just now',
      isResubmission: false,
      memberId: 'MEM-018',
      phone: '(555) 999-0000',
      aiSuggestions: [
        {
          type: 'modifier',
          add: '-95',
          reason: 'Telehealth visit billed without required 95 modifier; add modifier 95 to meet payer telehealth billing rules.',
          confidence: 88,
        },
      ],
    },
  ],
  [
    {
      id: 19,
      patient: 'Ava Collins',
      dob: '05/19/1989',
      serviceDate: '01/04/2025',
      provider: 'Dr. Patel',
      facility: 'Telehealth Clinic',
      mode: 'Telehealth',
      providerState: 'CA',
      patientState: 'TX',
      cpt: ['90837'],
      modifiers: ['-95'],
      icd10: ['F41.1'],
      amount: 200,
      payer: 'Blue Cross',
      stage: 'ai-review',
      status: 'Reviewing telehealth compliance',
      timeInStage: 'Just now',
      isResubmission: false,
      memberId: 'MEM-019',
      phone: '(555) 888-9999',
      telehealthPlatform: 'Zoom for Healthcare',
      aiSuggestions: [],
    },
  ],
];

export const tasks: Task[] = [
  {
    id: 't1',
    claimId: 13,
    patient: 'Rachel Green',
    dob: '03/08/1985',
    payer: 'Aetna',
    amount: 150,
    type: 'rejected',
    stage: 'Claim Submitted',
    reason: 'COB-123: Missing coordination of benefits',
    priority: 'P1',
    waiting: '3d',
    waitingMinutes: 4320,
    assignedTo: null,
    slaBreached: true,
  },
  {
    id: 't2',
    claimId: 5,
    patient: 'Amanda Foster',
    dob: '09/14/1995',
    payer: 'Aetna',
    amount: 150,
    type: 'human-review',
    stage: 'Human Approval',
    reason: '3 AI suggestions to review',
    priority: 'P1',
    waiting: '4h',
    waitingMinutes: 240,
    assignedTo: null,
    slaBreached: false,
  },
  {
    id: 't3',
    claimId: 14,
    patient: 'Daniel Lee',
    dob: '07/17/1972',
    payer: 'Medicare',
    amount: 200,
    type: 'rejected',
    stage: 'Claim Submitted',
    reason: 'MOD-456: Invalid modifier combination',
    priority: 'P1',
    waiting: '4d',
    waitingMinutes: 5760,
    assignedTo: 'Sarah M.',
    slaBreached: true,
  },
  {
    id: 't4',
    claimId: 6,
    patient: 'James Liu',
    dob: '02/28/1980',
    payer: 'Medicare',
    amount: 200,
    type: 'human-review',
    stage: 'Human Approval',
    reason: '1 AI suggestion to review',
    priority: 'P2',
    waiting: '4h',
    waitingMinutes: 240,
    assignedTo: null,
    slaBreached: false,
  },
  {
    id: 't5',
    claimId: 9,
    patient: 'Emily Watson',
    dob: '11/03/1992',
    payer: 'Aetna',
    amount: 150,
    type: 'expert-review',
    stage: 'Human Approval',
    reason: 'AI low confidence - complex modifier scenario',
    priority: 'P2',
    waiting: '3h',
    waitingMinutes: 180,
    assignedTo: 'Mike R.',
    slaBreached: false,
  },
  {
    id: 't6',
    claimId: 7,
    patient: 'Lisa Martinez',
    dob: '04/18/1988',
    payer: 'United',
    amount: 150,
    type: 'ready-submit',
    stage: 'Human Approval',
    reason: 'Changes approved - Ready to submit',
    priority: 'P2',
    waiting: '6h',
    waitingMinutes: 360,
    assignedTo: 'Sarah M.',
    slaBreached: false,
  },
  {
    id: 't7',
    claimId: 8,
    patient: 'Robert Kim',
    dob: '12/01/1970',
    payer: 'Cigna',
    amount: 250,
    type: 'ready-submit',
    stage: 'Human Approval',
    reason: 'Partial approval - Ready to submit',
    priority: 'P2',
    waiting: '1d',
    waitingMinutes: 1440,
    assignedTo: null,
    slaBreached: false,
  },
];

export const teamMembers = ['Sarah M.', 'Mike R.', 'Jane D.', 'Tom S.'];

